### ISSUE TITLE
Add authors and contributors to practice exercises

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/v3-launch#24]
With v3, we've introduced the idea of exercise authors and contributors. This information is stored in the exercise's `.meta/config.json` file (see [the docs](https://github.com/exercism/docs/blob/main/anatomy/tracks/practice-exercises.md#file-metaconfigjson)).

Concept Exercises, which are all new, have all defined their authors and contributors. Practice Exercises though are missing this information. We will try to automatically populate the authors and contributors of Practice Exercises based on the commit history.

**Comment by iHiD** [comment]
(cc @exercism/track-maintainers @exercism/alumni - You may want to check the PRs above that contain work you have done to ensure you are properly credited for your contributions 💙)

**Comment by verdammelt** [comment]
Not sure how many this may affect but (and i'm guessing) because only "known" renames are tracked the rename from Feb 2014 where exercises were moved out of an `assignments` subdirectory isn't noticed so some exercises will be marked as authored by Katrina.

**Comment by ErikSchierboom** [comment]
@verdammelt Hmmm, weird. My script _does_ take those renames into account. I'll have to look into it.

**Comment by ErikSchierboom** [comment]
@verdammelt I know what's happening. The problem is that the _track_ was renamed. It used to be named `lisp` instead of `common-lisp`.

**Comment by devkabiir** [comment]
Hello 👋  @ErikSchierboom, does your script skip exercism/dart?

**Comment by ErikSchierboom** [comment]
> does your script skip exercism/dart?

@devkabiir No my script does not skip dart. I've looked into this, and the PR was not created because the `v3-migration 🤖` label could not be found. I though I had created that label for all tracks, but I guess not. I've just re-added the label and re-run my script, leading to the PR being opened: https://github.com/exercism/dart/pull/310

> This makes me wonder, what about authors/contributors who changed their username?

Changing their username should not be an issue, as we lookup the username from the git commit author email.

**Comment by Stargator** [comment]
@ErikSchierboom I believe @devkabiir used to be @kabiir which shows up in the generated PR in exercise/dart alongside his current I'd @devkabiir.

So I don't know if we should simplify it to his current username. Whatever@devkabiir would prefer.

**Comment by devkabiir** [comment]
> Changing their username should not be an issue, as we lookup the username from the git commit author email.

For my case, I changed my username from `kabiir` to `devkabiir`. I suspect, `kabiir` was made available after some time as a valid username and someone did take it. This is a mistaken identity case. So if there are other contributors/authors with username changes or email changes, please be aware of this.

I do not know the exact way email lookup works, I think GitHub provides pseudo-anonymized emails like `<####-username@users.noreply.github.com>` or something like `<####@users.noreply.github.com>` _in some cases_. In any case could it be possible to automatically create PR-comments with details of username-misses or email-misses, for the `dart` track I almost know all of the contributor names and authors, but for tracks with higher traffic/commits they might require more efforts.

**Comment by ErikSchierboom** [comment]
Aha, like that. Thanks for the info
