### ISSUE TITLE
Add Ace editor and highlightjs languages to config.json

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/v3-launch#32]
Add two new keys to the `online_editor` property in the `config.json` files:

1. `ace_editor_language`: the language identifier for the Ace editor that is used to edit code on the website
2. `highlightjs_language`: the language identifier for Highlight.js which is used to highlight code on the website

For more information, see https://github.com/exercism/docs/pull/124/files

**Comment by hiljusti** [comment]
I'm merging for Factor and Zig, but these languages aren't supported by either editor.

Is it safe to assume that returning an unsupported value will not fail horribly, but just drop into plain text editing with no syntax highlighting?

**Comment by ErikSchierboom** [comment]
I think that was the case, right @kntsoriano?

**Comment by kntsoriano** [comment]
@ErikSchierboom Yes. Just no syntax highlighting.

**Comment by hiljusti** [comment]
Thanks!
‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
