### ISSUE TITLE
Remove `online_editor.ace_editor_language` key

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/v3-launch#40]
Having switched to CodeMirror, we no longer use the `ace_editor_language`. The `online_editor.ace_editor_language` key should thus be removed.

**Comment by ee7** [comment]
Is it worth re-running the `configlet lint` job on all these PRs, now that the latest release of configlet doesn't complain about the missing key? 

Do we have a little script to trigger that? Might be useful for the future.

**Comment by ErikSchierboom** [comment]
> Is it worth re-running the configlet lint job on all these PRs, now that the latest release of configlet doesn't complain about the missing key?

Probably not worth it, as we'll bulk merge them anyway (which doesn't need the workflow to pass).

> Do we have a little script to trigger that? Might be useful for the future.

I don't think we do.
