### ISSUE TITLE
Remove empty `source` and `source_url` properties

### ISSUE THREAD

**Issue by ee7** [exercism/v3-launch#57]
The [spec](https://github.com/exercism/docs/blob/113c070dfe944b7e360e5226ce264e99d3ca880e/building/configlet/lint.md#rule-exercisesconceptslugmetaconfigjson-is-valid) says that the `.meta/config.json` file for a Concept Exercise or a Practice Exercise should follow these rules:

> - The `source` key is optional
> - The `source` value must be a non-blank string¹
> - The `source_url` key is optional
> - The `source_url` value must be a URL
>
> Glossary:
> 1. Non-blank string: a string that contains at least one non-whitespace character.

In the latest configlet release (`4.0.0-alpha.26`), `configlet lint` now checks those rules - see https://github.com/exercism/configlet/commit/f548a732456a6f5b915dae99fbfa88aaf347d611.

And @ErikSchierboom says that `configlet lint` should indeed complain about an optional string key that has the value of the empty string - see https://github.com/exercism/configlet/pull/400#pullrequestreview-739348534.

So we should remove `source` and `source_url` properties where the value is the empty string. Otherwise, it will cause track CI to fail with a message like:

> The `source_url` value is the empty string, but it must be a valid URL:
> ./exercises/practice/robot-simulator/.meta/config.json

---

I'll create the PRs.

**Comment by ErikSchierboom** [comment]
All merged! Thanks @ee7?
